# Generated by Django 5.1.1 on 2024-10-03 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='port',
            field=models.PositiveIntegerField(default=80),
        ),
    ]
