# Generated by Django 5.1.1 on 2024-10-08 06:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0002_server_port'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhysicalServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('server_model', models.CharField(blank=True, max_length=255, null=True)),
                ('specs', models.CharField(blank=True, max_length=2455, null=True)),
                ('ram', models.CharField(blank=True, max_length=50, null=True)),
                ('hdd', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='VirtualServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('ip_address', models.GenericIPAddressField()),
                ('processor', models.CharField(blank=True, max_length=255, null=True)),
                ('ram', models.CharField(blank=True, max_length=255, null=True)),
                ('hdd', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('physical_server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.physicalserver')),
            ],
        ),
    ]
