# Generated by Django 5.1.1 on 2024-10-09 04:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0003_physicalserver_virtualserver'),
    ]

    operations = [
        migrations.AddField(
            model_name='virtualserver',
            name='port',
            field=models.PositiveIntegerField(default=80),
        ),
        migrations.AlterField(
            model_name='serverstatus',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.virtualserver'),
        ),
    ]
