# Generated by Django 5.1.1 on 2024-10-09 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0004_virtualserver_port_alter_serverstatus_server'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Server',
        ),
    ]
