# Generated by Django 5.1.1 on 2024-10-09 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0005_delete_server'),
    ]

    operations = [
        migrations.AddField(
            model_name='physicalserver',
            name='server_type',
            field=models.CharField(default='CPU', max_length=100),
        ),
    ]
