# Generated by Django 5.1.1 on 2024-10-09 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0006_physicalserver_server_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='virtualserver',
            name='server_type',
            field=models.CharField(default='', max_length=100),
        ),
    ]
