# Generated by Django 5.1.1 on 2024-10-10 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0007_virtualserver_server_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='virtualserver',
            old_name='server_type',
            new_name='group',
        ),
    ]
