# Generated by Django 5.1.1 on 2024-10-16 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0008_rename_server_type_virtualserver_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='virtualserver',
            name='active_connections',
            field=models.IntegerField(default=0),
        ),
    ]
