# Generated by Django 5.1.1 on 2024-10-16 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0009_virtualserver_active_connections'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='virtualserver',
            name='active_connections',
        ),
        migrations.AddField(
            model_name='serverstatus',
            name='active_connections',
            field=models.IntegerField(default=0),
        ),
    ]
