# Generated by Django 5.1.1 on 2024-10-29 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0010_remove_virtualserver_active_connections_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serverstatus',
            name='response_time',
            field=models.FloatField(default=0.0),
        ),
    ]
