# Generated by Django 5.1.1 on 2025-02-04 05:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0011_serverstatus_response_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServerStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('down_datetime', models.DateTimeField()),
                ('up_datetime', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.virtualserver')),
            ],
        ),
    ]
