# Generated by Django 5.1.1 on 2025-02-04 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0012_serverstatushistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serverstatushistory',
            name='down_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='serverstatushistory',
            name='up_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
